### PR TITLE
Updated all references to the correct GH organization and repo

### PR DESCRIPTION
**Pull request by ringods**
Updated all links to GH issues, GH organization and repository are updated to reflect the current state:
* GH org: `davidsneighbour` instead of `dnb-org`
* GH repo: `hugo-hooks` instead of `hooks` or `dnb-hugo-hooks`

I left the `@dnb-org` as the namespace in the NPM depencencies in `package.json` for now, as I didn't know what you intend to do with this.

Signed-off-by: Ringo De Smet <ringo@de-smet.name>

### CODE REVIEW

**Review by davidsneighbour — APPROVED** [review]

**Comment by ringods** [comment]
@davidsneighbour in this repo, on it's main page, there is an `About` section still pointing to the `dnb-org` GH organisation. Can you update the link as well there?

**Comment by davidsneighbour** [comment]
I am going through all repos and update it. As far as I went it's as easy as just replacing `dnb-org/dnb-` with `davidsneighbour/` check and then running a release. If you send PRs I'll merge them.

**Comment by davidsneighbour** [comment]
PRs with fixes. You can't run a release I think.

**Comment by ringods** [comment]
@davidsneighbour I'm willing to contribute more PRs, but your release process is still adding the old links into the CHANGELOG.md file:

https://github.com/davidsneighbour/hugo-hooks/commit/f9998b4d5127e6423a66d3e3c588fa3eca9b7867

Would this be solved by changing the `devDependencies` from `@dnb-org/standard-version-config` to the newer `@davidsneighbour/standard-version-config`?

**Comment by davidsneighbour** [comment]
I think the CHANGELOG.md uses my local Git info and I might not have switched the remotes yet properly.

I am not happy about these changelogs, they are way too large after some releases. Might be even cutting them down a bit. I have the idea, that something in my local setup still uses dnb-org, will check that and rerelease. Old links in that file to dnb-org are ok IMHO.

**Pull request merged**
